---
- name: iBGP base config for leafs (NXOS)
  connection: network_cli
  cli_config:
    config: |
      router bgp {{ ibgp_asn }}
         log-neighbor-changes
         address-family l2vpn evpn
           advertise-pip
         template peer VXLAN_SPINE
           remote-as {{ ibgp_asn }}
           update-source loopback0
           address-family l2vpn evpn
              send-community
              send-community extended
  when: inventory_hostname not in groups['spine']              
         
- name: iBGP neighbor config for leafs (NXOS)
  connection: network_cli
  cli_config:
    config: |
      router bgp {{ ibgp_asn }}
        neighbor {{ item }}
          inherit peer VXLAN_SPINE
  with_items: "{{ evpn_peers }}"
  when: inventory_hostname not in groups['spine']

- name: iBGP neighbor config for spines (NXOS)
  connection: network_cli
  cli_config:
    config: |
      router bgp {{ ibgp_asn }}
         log-neighbor-changes
         address-family l2vpn evpn
           retain route-target all
         neighbor 10.0.0.0/24
           remote-as {{ ibgp_asn }}
           update-source loopback0
           address-family l2vpn evpn
              send-community
              send-community extended
              route-reflector-client
  with_items: "{{ evpn_peers }}"
  when: inventory_hostname in groups['spine']

- name: Route map for L3 VNI adv
  connection: network_cli
  cli_config:
    config: |
      route-map ADV_SVIS permit 10
        match tag 12345

- name: Advertise L3 GW address (NXOS)                                                                  
  connection: network_cli                          
  cli_config:                                                                                           
    config: |
      router bgp {{ ibgp_asn }}                    
        vrf {{ l2_networks[item.vlanid].vrf }}                                                          
          log-neighbor-changes                                                                          
          address-family ipv4 unicast                                                                   
            redistribute direct route-map ADV_SVIS
            maximum-paths ibgp 4
                                                                                                        
  with_items: "{{ l2_ports[ansible_network_os] }}"                                                      
  when: l2_ports is defined                                  
